name: Redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      DEPLOY_HOOK: ${{ github.ref == 'refs/heads/main' && secrets.WEBSITE_DEPLOY_HOOK || secrets.WEBSITE_DEPLOY_HOOK_CORE_1 }}
    steps:
      - name: Check for dont-redeploy label
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |

            console.log(context)
            console.log(context.payload)
            console.log(context.payload.pull_request)

            // For workflow_dispatch or direct pushes without PRs, we should always deploy
            if (!context.payload.pull_request) {
              console.log('No PR associated with this commit, deploying');
              return {shouldDeploy: true};
            }

            // Get the PR associated with this commit (if any)
            const associatedPRs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha
            });

            console.log(associatedPRs)
            console.log(associatedPRs.data)

            if (associatedPRs.data.length === 0) {
              // No associated PR found, safe to deploy
              console.log('No PR associated with this commit, deploying');
              return {shouldDeploy: true};
            }

            // Check the labels on the associated PR
            const pr = associatedPRs.data[0];
            const hasDoNotDeployLabel = pr.labels.some(label => label.name === 'dont-redeploy');

            console.log(`PR ${pr.number} has ${hasDoNotDeployLabel ? '' : 'no'} "dont-redeploy" label`);
            return {shouldDeploy: !hasDoNotDeployLabel};

      - name: print result
        run: |
          echo "shouldDeploy: ${{ fromJSON(steps.check-label.outputs.result).shouldDeploy }}"

      - name: Trigger redeploy
        if: ${{ fromJSON(steps.check-label.outputs.result).shouldDeploy }}
        run: |
          echo "Triggering redeploy..."
